version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: pictoapp_php
    hostname: pictoapp_php
    volumes:
      - ../:/var/www/html
    ports:
      - "9001:80"
    depends_on:
      - db
    working_dir: /var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    command: /bin/bash -c "apt-get update && apt-get install -y unzip git curl && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: pictoapp_mysql_db
    hostname: pictoapp_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: abc123.
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db_data:


